import { pickDict, UI_LANG } from '../locale'

const pl = {
  title: 'Akademia U21',
  intro:
    'Rozwijaj juniorów: od obserwacji, przez akademię, do pierwszego składu. Jesienią i wiosną oceniaj kandydatów z nowej fali naboru.',
  academyLevelLabel: (level) => `Poziom akademii: ${level}/10`,
  prospectsTitle: 'Zawodnicy akademii',
  prospectsEmpty: 'Akademia jest pusta. Przyjmij obserwowanego juniora, poczekaj na wrześniowy lub marcowy nabór albo wyślij skauta.',
  colPlayer: 'Zawodnik',
  colAge: 'Wiek',
  colOvr: 'OVR',
  colPotential: 'Potencjał',
  colSource: 'Źródło',
  colJoined: 'Sezon naboru',
  sourceIntake: 'Nabór',
  sourceScouted: 'Skauting',
  ageOutWarning: (age) => (age >= 20 ? `Uwaga: ${age} lat — niedługo wygaśnie termin` : null),
  promoteAction: 'Awansuj do seniorów',
  releaseAction: 'Zwolnij',
  promoteConfirmError: 'Nie udało się awansować zawodnika (brak budżetu lub warunków kontraktu).',
  sendScoutTitle: 'Wyślij skauta za granicę',
  continentLabel: 'Kontynent',
  europeRegionLabel: 'Region Europy',
  countryLabel: 'Kraj',
  countryPlaceholder: 'Wybierz kraj…',
  durationLabel: 'Długość wyjazdu',
  monthsOption: (n) => (n === 1 ? '1 miesiąc' : n < 5 ? `${n} miesiące` : `${n} miesięcy`),
  sendScoutButton: 'Wyślij skauta',
  scoutQueued: 'Skaut wysłany — pierwszy raport przyjdzie za miesiąc.',
  errorMissingCountry: 'Wybierz kraj przed wysłaniem skauta.',
  errorInvalidDuration: 'Wybierz długość wyjazdu.',
  errorCapacity: 'Brak wolnych slotów skautingu — rozbuduj dział skautingu albo poczekaj na zakończenie misji.',
  errorInsufficientFunds: 'Za mało środków w budżecie transferowym.',
  errorGeneric: 'Nie udało się wysłać skauta.',
  pendingMissionsTitle: 'Wyjazdy w toku',
  noPendingMissions: 'Brak aktywnych wyjazdów skautingowych po prospektów.',
  monthProgress: (n, total) => `Miesiąc ${n}/${total} obserwacji`,
  candidatesTitle: 'Obserwowani juniorzy',
  candidatesHint: 'To jeszcze nie są zawodnicy klubu. Zleć dalszą obserwację, aby poznać ich umiejętności, a następnie zdecyduj o przyjęciu do akademii.',
  candidatesEmpty: 'Brak obserwowanych juniorów. Kolejne fale naboru: 1 września i 1 marca; możesz też wysłać skauta.',
  colKnowledge: 'Znajomość',
  colCountry: 'Kraj',
  colPotentialShort: 'Potencjał',
  signAction: 'Sprowadź do akademii',
  rejectAction: 'Odrzuć',
  keepObservingAction: 'Obserwuj dalej',
  keepObservingPending: 'Obserwacja w toku…',
  recallAction: 'Odwołaj skauta',
  recalling: 'Skaut wraca do domu…',
}

const en = {
  title: 'U21 Academy',
  intro:
    'Develop juniors from observation through the academy to the first team. Review new intake candidates each autumn and spring.',
  academyLevelLabel: (level) => `Academy level: ${level}/10`,
  prospectsTitle: 'Academy players',
  prospectsEmpty: 'The academy is empty. Recruit an observed junior, wait for the September or March intake, or send a scout.',
  colPlayer: 'Player',
  colAge: 'Age',
  colOvr: 'OVR',
  colPotential: 'Potential',
  colSource: 'Source',
  colJoined: 'Intake season',
  sourceIntake: 'Intake',
  sourceScouted: 'Scouted',
  ageOutWarning: (age) => (age >= 20 ? `Heads up: age ${age} — deadline approaching` : null),
  promoteAction: 'Promote to first team',
  releaseAction: 'Release',
  promoteConfirmError: 'Could not promote the player (budget or contract terms failed).',
  sendScoutTitle: 'Send a scout abroad',
  continentLabel: 'Continent',
  europeRegionLabel: 'European region',
  countryLabel: 'Country',
  countryPlaceholder: 'Choose a country…',
  durationLabel: 'Trip length',
  monthsOption: (n) => (n === 1 ? '1 month' : `${n} months`),
  sendScoutButton: 'Send scout',
  scoutQueued: 'Scout sent — first report lands in a month.',
  errorMissingCountry: 'Pick a country before sending the scout.',
  errorInvalidDuration: 'Pick a trip length.',
  errorCapacity: 'No free scouting slots — upgrade the scouting department or wait for a mission to finish.',
  errorInsufficientFunds: 'Not enough transfer budget.',
  errorGeneric: 'Could not send the scout.',
  pendingMissionsTitle: 'Trips in progress',
  noPendingMissions: 'No active academy scouting trips.',
  monthProgress: (n, total) => `Month ${n}/${total} of observation`,
  candidatesTitle: 'Observed juniors',
  candidatesHint: 'These juniors do not belong to the club yet. Assign further observation to assess their skills, then decide whom to recruit into the academy.',
  candidatesEmpty: 'No observed juniors. Intake waves arrive on 1 September and 1 March; you can also send a scout.',
  colKnowledge: 'Knowledge',
  colCountry: 'Country',
  colPotentialShort: 'Potential',
  signAction: 'Sign to academy',
  rejectAction: 'Reject',
  keepObservingAction: 'Keep observing',
  keepObservingPending: 'Observation in progress…',
  recallAction: 'Recall scout',
  recalling: 'Scout heading home…',
}

export function academyStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
