import { pickDict, UI_LANG } from '../locale'

const pl = {
  loading: 'Ładowanie…',
  loadingCareer: 'Ładowanie kariery…',
  back: 'Wróć',
  cancel: 'Anuluj',
  save: 'Zapisz',
  show: 'Pokaż',
  hide: 'Ukryj',
  all: 'Wszyscy',
  allF: 'Wszystkie',
  sort: 'Sortuj',
  team: 'Drużyna',
  player: 'Zawodnik',
  players: 'Zawodnicy',
  wins: 'Zwycięstwa',
  losses: 'Porażki',
  emptyDash: '—',
  yes: 'Tak',
  no: 'Nie',
  close: 'Zamknij',
  more: 'Więcej',
  less: 'Zwiń',
  today: 'dziś',
  next: 'Dalej',
  previous: 'Wstecz',
  weekdaysShort: ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'So'],
  weekdays: [
    'Niedziela',
    'Poniedziałek',
    'Wtorek',
    'Środa',
    'Czwartek',
    'Piątek',
    'Sobota',
  ],
  phases: {
    fall: 'Jesień (liga)',
    cup: 'Puchar stycznia',
    spring: 'Wiosna (liga)',
    offseason: 'Offseason',
  },
  simulation: 'Symulacja',
  simulationEllipsis: 'Symulacja…',
  processing: 'Przetwarzanie…',
}

const en = {
  loading: 'Loading…',
  loadingCareer: 'Loading career…',
  back: 'Back',
  cancel: 'Cancel',
  save: 'Save',
  show: 'Show',
  hide: 'Hide',
  all: 'All',
  allF: 'All',
  sort: 'Sort',
  team: 'Team',
  player: 'Player',
  players: 'Players',
  wins: 'Wins',
  losses: 'Losses',
  emptyDash: '—',
  yes: 'Yes',
  no: 'No',
  close: 'Close',
  more: 'More',
  less: 'Collapse',
  today: 'today',
  next: 'Next',
  previous: 'Back',
  weekdaysShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
  weekdays: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  ],
  phases: {
    fall: 'Fall (league)',
    cup: 'January Cup',
    spring: 'Spring (league)',
    offseason: 'Offseason',
  },
  simulation: 'Simulation',
  simulationEllipsis: 'Simulating…',
  processing: 'Processing…',
}

export function commonStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
