import { pickDict, UI_LANG } from '../locale'

const pl = {
  inboxTitle: (n) => `Skrzynka · ${n} ${n === 1 ? 'nowa wiadomość' : 'nowych wiadomości'}`,
  inboxHint: 'Raporty treningowe, oferty transferowe i analizy pomeczowe czekają na odczyt',
  openInbox: 'Otwórz skrzynkę',
  newsBrand: 'Ultizone.com',
  newsNew: (n) => ` · ${n} nowych`,
  readPortal: 'Czytaj portal',
  transferNegotiate: 'Możesz negocjować transfery',
  transferBudget: (usd) => ` · budżet transferowy ${usd}`,
  salaryBudget: (usd) => ` · pensje ${usd}`,
  transferSummerRange: ' · 1 lipca – 31 sierpnia',
  openTransfers: 'Otwórz transfery',
  calendarTitle: (season) => `Kalendarz · ${season}`,
  phase: 'Faza',
  leagueRound: (cur, total) => `kolejka ligowa ~${cur}/${total}`,
  careerIndex: (n) => ` · kariera #${n}`,
  cup: 'Puchar',
  nextDay: 'Dalej',
  simUntilMatch: 'Symuluj do mojego meczu',
  simulating: 'Symulacja…',
  actionRequired: 'Wymaga decyzji',
  yourMatch: 'Twój mecz',
  competitionCup: 'Puchar',
  competitionLeague: 'Liga',
  goToMatch: 'Przejdź do meczu',
  todaysMatches: 'Dzisiejsze mecze',
  noMatchesToday: 'Brak meczów w tym dniu.',
  cupTag: 'puchar',
  play: 'Graj',
  shortcuts: 'Skróty',
  catHome: 'Strona główna',
  catTeam: 'Drużyna',
  catSeason: 'Sezon',
  catNews: 'Ultizone',
  shortcutInbox: 'Skrzynka odbiorcza →',
  shortcutNextMatch: 'Następny mecz →',
  shortcutTactics: 'Taktyka · O-Line / D-Line →',
  shortcutRoster: 'Skład →',
  shortcutTraining: 'Trening i rozwój →',
  shortcutClubBoard: 'Zarząd · struktury i sponsorzy →',
  shortcutTeamSchedule: 'Terminarz drużyny →',
  shortcutCalendar: 'Kalendarz →',
  shortcutTransfers: 'Centrum transferowe',
  windowOpen: ' (okno otwarte)',
  shortcutStandings: 'Pełna tabela ligowa →',
  shortcutLeagueSchedule: 'Terminarz ligi →',
  shortcutLeaders: 'Liderzy ligowi →',
  shortcutLeagueTransfers: 'Transfery ligowe →',
  shortcutCup: 'Puchar Ligi →',
  shortcutNews: 'Ultizone →',
  yourTeam: 'Twoja drużyna',
  place: 'Miejsce',
  reputation: 'Reputacja',
  fans: 'Kibice',
  fanMood: 'Nastrój trybun',
  homeBonus: 'Premia gospodarza aktywna · 30 kolejek (każdy z każdym u siebie i na wyjeździe)',
}

const en = {
  inboxTitle: (n) => `Inbox · ${n} new message${n === 1 ? '' : 's'}`,
  inboxHint: 'Training reports, transfer offers and post-match analysis await',
  openInbox: 'Open inbox',
  newsBrand: 'Ultiworld.com',
  newsNew: (n) => ` · ${n} new`,
  readPortal: 'Read portal',
  transferNegotiate: 'You can negotiate transfers',
  transferBudget: (usd) => ` · transfer budget ${usd}`,
  salaryBudget: (usd) => ` · wages ${usd}`,
  transferSummerRange: ' · 1 Jul – 31 Aug',
  openTransfers: 'Open transfers',
  calendarTitle: (season) => `Calendar · ${season}`,
  phase: 'Phase',
  leagueRound: (cur, total) => `league round ~${cur}/${total}`,
  careerIndex: (n) => ` · career #${n}`,
  cup: 'Cup',
  nextDay: 'Next',
  simUntilMatch: 'Sim until my match',
  simulating: 'Simulating…',
  actionRequired: 'Action required',
  yourMatch: 'Your match',
  competitionCup: 'Cup',
  competitionLeague: 'League',
  goToMatch: 'Go to match',
  todaysMatches: "Today's matches",
  noMatchesToday: 'No matches on this day.',
  cupTag: 'cup',
  play: 'Play',
  shortcuts: 'Shortcuts',
  catHome: 'Home',
  catTeam: 'Team',
  catSeason: 'Season',
  catNews: 'Ultiworld',
  shortcutInbox: 'Inbox →',
  shortcutNextMatch: 'Next match →',
  shortcutTactics: 'Tactics · O-Line / D-Line →',
  shortcutRoster: 'Roster →',
  shortcutTraining: 'Training & development →',
  shortcutClubBoard: 'Board · facilities & sponsors →',
  shortcutTeamSchedule: 'Team schedule →',
  shortcutCalendar: 'Calendar →',
  shortcutTransfers: 'Transfer center',
  windowOpen: ' (window open)',
  shortcutStandings: 'Full league table →',
  shortcutLeagueSchedule: 'League schedule →',
  shortcutLeaders: 'League leaders →',
  shortcutLeagueTransfers: 'League transfers →',
  shortcutCup: 'League Cup →',
  shortcutNews: 'Ultiworld →',
  yourTeam: 'Your team',
  place: 'Place',
  reputation: 'Reputation',
  fans: 'Fans',
  fanMood: 'Fan mood',
  homeBonus: 'Home advantage active · 30 rounds (home and away vs every team)',
}

export function hubStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
