import { pickDict, UI_LANG } from '../locale'

const pl = {
  title: 'Skrzynka',
  empty: 'Skrzynka jest pusta — raporty treningowe, oferty i analizy pojawią się tutaj.',
  pickMessage: 'Wybierz wiadomość z listy.',
  markAllRead: 'Oznacz przeczytane',
  filters: {
    all: 'Wszystkie',
    unread: 'Nieprzeczytane',
    training: 'Trening',
    transfers: 'Transfery',
    match: 'Mecz',
    injuries: 'Kontuzje',
    events: 'Zdarzenia',
    club: 'Klub',
    scouting: 'Scouting',
  },
  offerStatus: {
    pending: 'Oczekuje',
    counter: 'Kontrpropozycja AI',
    accepted: 'Zaakceptowana',
    rejected: 'Odrzucona',
    expired: 'Wygasła',
    withdrawn: 'Wycofana',
    awaiting_reply: 'Oczekuje na odpowiedź',
    club_agreed: 'Zgoda klubu — kontrakt',
    pre_agreed: 'Umowa wstępna',
    pending_confirm: 'Potwierdź rejestrację',
    superseded: 'Zastąpiona',
  },
  replyBy: 'Odpowiedź do',
  proposeContract: 'Wyślij ofertę kontraktu',
  acceptClubCounter: 'Akceptuj kontrpropozycję klubu',
  acceptPlayerCounter: 'Akceptuj warunki zawodnika',
  confirmRegistration: 'Potwierdź rejestrację',
  declineRegistration: 'Anuluj umowę',
  preAgreedHint:
    'Umowa wstępna — transfer zarejestrujesz po otwarciu okna (osobna wiadomość w skrzynce).',
  registrationHint:
    'Okno jest otwarte. Potwierdź, aby zarejestrować transfer — bez potwierdzenia się nie odbędzie.',
  contractWeekly: 'Tygodniówka',
  contractYears: 'Lata',
  contractTotal: 'Łączny koszt',
  awaitingClub: 'Czekasz na odpowiedź klubu…',
  awaitingPlayer: 'Czekasz na odpowiedź zawodnika…',
  awaitingBuyer: 'Czekasz na odpowiedź kupującego…',
  bonuses: 'Bonusy',
  promises: 'Obietnice',
  setDemand: 'Ustaw oczekiwania',
  feeAgreed: 'Kwota transferu',
  willingness: 'Chęć przenosin',
  currentWage: 'Obecna pensja',
  demandedWage: 'Oczekiwana pensja',
  incomingOffer: 'Oferta przychodząca',
  expires: 'Ważna do',
  buyer: 'Kupujący',
  currentOffer: 'Aktualna oferta',
  yourAsk: 'Twój ask',
  accept: 'Akceptuj',
  reject: 'Odrzuć',
  counter: 'Kontroferta',
  counterLabel: 'Twoja kontrpropozycja (USD)',
  sendCounter: 'Wyślij kontrofertę',
  resolved: 'Rozstrzygnięte',
  goTo: 'Przejdź do',
  fullBoxScore: 'Pełny box score',
  hideBoxScore: 'Ukryj pełny box score',
  best3: '3 najlepsi',
  worst3: '3 najsłabsi',
  unreadBadge: 'nowe',
  deleteMessage: 'Usuń wiadomość',
  noFilter: 'Brak wiadomości w tym filtrze.',
  counterLabelShort: 'Kontrpropozycja (USD)',
  sendCounterShort: 'Wyślij kontrę',
  counterHint:
    'AI oceni Twoją kwotę względem budżetu i jakości zawodnika. Zbyt wysoka oferta kończy rozmowy; blisko ich maksimum mogą podnieść swoją.',
  windowClosedNeg:
    'Okno transferowe jest zamknięte — nie możesz negocjować.',
  teamStats: 'Statystyki drużynowe',
  completionYou: '% podań (Ty)',
  completionOpp: '% podań (rywal)',
  odHint: 'O = punkt zdobyty po rozpoczęciu w ataku · D = po rozpoczęciu w obronie',
  simNoStats: 'Mecz z symulacji — szczegółowe statystyki niedostępne.',
  noDetailedStats: 'Szczegółowe statystyki niedostępne dla tej analizy.',
  quality: 'Jakość',
  engagement: 'Zaangażowanie',
  unavailable: 'Niedostępny',
  source: 'Źródło',
  negotiateError: 'Błąd negocjacji',
  youngTarget: ' — cel: młody talent',
  needsDecision: 'Wymaga decyzji',
  dealSaved: 'Transfer zapisany w historii klubu.',
  attendance: 'Frekwencja',
  skillBumps: 'Skoki skilli',
  injuryLabel: 'Uraz',
}

const en = {
  title: 'Inbox',
  empty: 'Inbox is empty — training reports, offers and analysis will show up here.',
  pickMessage: 'Pick a message from the list.',
  markAllRead: 'Mark all read',
  filters: {
    all: 'All',
    unread: 'Unread',
    training: 'Training',
    transfers: 'Transfers',
    match: 'Match',
    injuries: 'Injuries',
    events: 'Events',
    club: 'Club',
    scouting: 'Scouting',
  },
  offerStatus: {
    pending: 'Pending',
    counter: 'AI counter',
    accepted: 'Accepted',
    rejected: 'Rejected',
    expired: 'Expired',
    withdrawn: 'Withdrawn',
    awaiting_reply: 'Awaiting reply',
    club_agreed: 'Club agreed — contract',
    pre_agreed: 'Pre-agreement',
    pending_confirm: 'Confirm registration',
    superseded: 'Superseded',
  },
  replyBy: 'Reply by',
  proposeContract: 'Send contract offer',
  acceptClubCounter: 'Accept club counter',
  acceptPlayerCounter: 'Accept player terms',
  confirmRegistration: 'Confirm registration',
  declineRegistration: 'Cancel deal',
  preAgreedHint:
    'Pre-agreement — you will register the transfer when the window opens (separate inbox message).',
  registrationHint:
    'The window is open. Confirm to register the transfer — it will not happen without confirmation.',
  contractWeekly: 'Weekly wage',
  contractYears: 'Years',
  contractTotal: 'Total cost',
  awaitingClub: 'Waiting for the club reply…',
  awaitingPlayer: 'Waiting for the player reply…',
  awaitingBuyer: 'Waiting for the buyer reply…',
  bonuses: 'Bonuses',
  promises: 'Promises',
  setDemand: 'Match demand',
  feeAgreed: 'Transfer fee',
  willingness: 'Willingness',
  currentWage: 'Current wage',
  demandedWage: 'Expected wage',
  incomingOffer: 'Incoming offer',
  expires: 'Expires',
  buyer: 'Buyer',
  currentOffer: 'Current offer',
  yourAsk: 'Your ask',
  accept: 'Accept',
  reject: 'Reject',
  counter: 'Counter',
  counterLabel: 'Your counter-offer (USD)',
  sendCounter: 'Send counter',
  resolved: 'Resolved',
  goTo: 'Go to',
  fullBoxScore: 'Full box score',
  hideBoxScore: 'Hide full box score',
  best3: 'Top 3',
  worst3: 'Bottom 3',
  unreadBadge: 'new',
  deleteMessage: 'Delete message',
  noFilter: 'No messages in this filter.',
  counterLabelShort: 'Counter-offer (USD)',
  sendCounterShort: 'Send counter',
  counterHint:
    'AI will judge your number against budget and player quality. Too high ends talks; near their max they may raise theirs.',
  windowClosedNeg: 'Transfer window is closed — you cannot negotiate.',
  teamStats: 'Team statistics',
  completionYou: 'Completion % (you)',
  completionOpp: 'Completion % (opp.)',
  odHint: 'O = scored starting on offense · D = scored starting on defense',
  simNoStats: 'Simulated match — detailed stats unavailable.',
  noDetailedStats: 'Detailed stats unavailable for this analysis.',
  quality: 'Quality',
  engagement: 'Engagement',
  unavailable: 'Unavailable',
  source: 'Source',
  negotiateError: 'Negotiation error',
  youngTarget: ' — young talent target',
  needsDecision: 'Decision required',
  dealSaved: 'Transfer saved to club history.',
  attendance: 'Attendance',
  skillBumps: 'Skill bumps',
  injuryLabel: 'Injury',
}

export function inboxStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
