import { pickDict, UI_LANG } from '../locale'

const pl = {
  leagueMatch: 'Mecz ligowy',
  simMatch: 'Symulacja meczu',
  playPoint1: 'Rozegraj punkt 1',
  playPoint: (n) => `Rozegraj punkt ${n}`,
  simRest: 'Symuluj cały mecz',
  switchPointByPoint: 'Tryb punkt po punkcie',
  simNextPoint: 'Symuluj kolejny punkt',
  simToEnd: 'Symuluj do końca meczu',
  changeTactics: 'Zmień taktykę',
  hideTactics: 'Ukryj taktykę',
  exitPointByPoint: 'Wróć do pełnego trybu',
  pause: 'Pauza',
  resume: 'Wznów',
  returnHub: 'Wróć do centrum ligi',
  resultSaved: 'Wynik zapisany w tabeli ligowej',
  matchOver: 'Mecz zakończony',
  prepTitle: 'Przygotowanie meczu — taktyka i siódemki',
  finishWithTactics: 'Dokańcz mecz z tą taktyką',
  injuredInLineup: (line, names) =>
    names?.length
      ? `${line}: kontuzjowany w składzie — ${names.join(', ')}.`
      : `${line}: kontuzjowany zawodnik w składzie.`,
  duplicateInLineup: (line) => `${line}: ten sam zawodnik nie może zajmować dwóch miejsc.`,
  needSeven: (line) => `${line}: wybierz 7 różnych zawodników.`,
  home: 'Gospodarze',
  away: 'Goście',
  eventStart: (pts, home, away) => `Start meczu · do ${pts} pkt · ${home} vs ${away}`,
  eventPointStart: (n, pull) => `— Punkt ${n} · pull: ${pull}`,
  eventPull: (team) => `Pull · ${team}`,
  eventPossession: (team, pos) => `Atak: ${team} (pozycja ${pos})`,
  eventStallOut: (team, pos) => `Stall-out · turnover · ${team} · poz. ${pos}`,
  eventTurnover: (team, pos) => `Turnover · ${team} · pozycja ${pos}`,
  eventScore: (team, reason) => `★ PUNKT · ${team}${reason ? ` (${reason})` : ''}`,
  eventPointEnd: (throws) => `Koniec punktu · ${throws} rzutów`,
  eventInjury: (name, label, days) => `Kontuzja · ${name} (${label}) · out ${days} dni`,
  eventMatchEnd: (hs, as_, winner) => `Koniec meczu · ${hs}:${as_} · zwycięzca: ${winner}`,
  fullThrowLog: 'Pełny log rzutów',
  throwsN: (n) => `${n} rzutów`,
  historyBelow: 'historia poniżej',
  pointsEvents: (pts, ev) => `${pts} punktów · ${ev} zdarzeń`,
  abbreviated: ' (skrócony)',
  matchStatsTitle: 'Statystyki meczowe',
  homeShort: 'Dom',
  awayShort: 'Gość',
  yardsFromThrows: 'Metry z podań',
  completions: 'Podania',
  hucks: 'Hucki (≥40 m)',
  turnovers: 'Turnovery',
  hold: 'Hold',
  break: 'Break',
  huckTitle: 'Rzut z postępem dysku ≥ 40 m',
  holdTitle: 'Odsetek punktów utrzymanych z własnego rozpoczęcia w ataku',
  breakTitle: 'Odsetek punktów odebranych przeciwnikowi z rozpoczęcia w obronie',
  pressureCompletions: 'Podania pod presją',
  pressureCompletionsTitle: 'Skuteczność podań oddanych przy wysokim stall count (pod presją markera)',
  pointHistoryTitle: 'Historia punktu',
  pointHistorySubtitle: 'Pełny przebieg rzutów i turnoverów',
  winnerLabel: 'zwycięzca',
  pointLabel: 'Punkt',
  personMatchups: (n) => `Person D · przypisania (${n} par)`,
  possessionChange: (team, pos) => `Zmiana posiadania → ${team} · poz. ${pos}`,
  personZoneFootnote: (zone) =>
    `Person: mark na odbiorcy · Zone: ${zone} — presja na kluczowym graczu`,
  staminaPanelTitle: 'Punkt',
  staminaPanelHint: 'stamina · 7 na boisku',
  playerCol: 'Zawodnik',
  thrAbbr: 'THR',
  thrTitle: 'Podania (udane/próby)',
  pctTitle: '% completions',
  tmTitle: 'Metry z rzutów',
  cmTitle: 'Metry złapanych',
  rmTitle: 'Przebiegnięty dystans (m)',
  toTitle: 'Turnovery',
  blocksTitle: 'Bloki',
  assistTag: 'asysta',
  goalTag: 'gol',
  statLegend: 'THR · % · Tm · Cm · Rm · TO · B',
  historyPointStart: (n, attack) => `Start punktu ${n} · atak: ${attack}`,
  boxScorersTitle: 'Punktujący w meczu',
  boxStatsTitle: 'Podsumowanie statystyk zawodników',
  boxScorersSubtitle: 'Tylko gole (G) · pełny box score po zakończeniu meczu',
  boxStatsSubtitle: 'Box Score · G / A / B (D-blocks) / TO / PP',
  boxScorersEmpty: 'Jeszcze nikt nie zdobył punktu (G). Pełne statystyki pojawią się po meczu.',
  teamCol: 'Drużyna',
  ppTitle: 'Punkty rozegrane',
  simTempo: 'Tempo symulacji:',
  newMatch: 'Nowy mecz',
  waitingAction: 'Oczekiwanie na akcję…',
  actionLabel: 'Akcja',
  phaseSetup: 'Ustawienie',
  phaseThrow: 'Rzut',
  phaseFlight: 'Lot',
  windLabel: (label) => `Wiatr ${label}`,
  attackShort: 'Atak',
  defenseShort: 'Obrona',
  pointByPointMatch: 'Mecz punkt po punkcie',
  matchLog: 'Log meczu',
  pointN: (n) => `Punkt ${n}:`,
  emptyField: 'Brak danych boiska',
  discPossession: (meters, team) =>
    `Dysk: ${meters} m · ${team} w posiadaniu`,
  matchupSubtitle: (homeName, homeCount, awayName, awayCount, pts) =>
    `${homeName} (${homeCount} zaw.) vs ${awayName} (${awayCount} zaw.) · do ${pts} pkt`,
  seedOptional: 'Seed (opcjonalnie)',
  seedRandomPlaceholder: 'losowo',
}

const en = {
  leagueMatch: 'League match',
  simMatch: 'Match simulation',
  playPoint1: 'Play point 1',
  playPoint: (n) => `Play point ${n}`,
  simRest: 'Simulate full match',
  switchPointByPoint: 'Point-by-point mode',
  simNextPoint: 'Simulate next point',
  simToEnd: 'Simulate to end of match',
  changeTactics: 'Change tactics',
  hideTactics: 'Hide tactics',
  exitPointByPoint: 'Return to full mode',
  pause: 'Pause',
  resume: 'Resume',
  returnHub: 'Back to league hub',
  resultSaved: 'Result saved to the league table',
  matchOver: 'Match finished',
  prepTitle: 'Match prep — tactics and lineups',
  finishWithTactics: 'Finish the match with this tactics',
  injuredInLineup: (line, names) =>
    names?.length
      ? `${line}: injured in lineup — ${names.join(', ')}.`
      : `${line}: injured player in the lineup.`,
  duplicateInLineup: (line) => `${line}: the same player cannot fill two slots.`,
  needSeven: (line) => `${line}: pick 7 different players.`,
  home: 'Home',
  away: 'Away',
  eventStart: (pts, home, away) => `Match start · to ${pts} pts · ${home} vs ${away}`,
  eventPointStart: (n, pull) => `— Point ${n} · pull: ${pull}`,
  eventPull: (team) => `Pull · ${team}`,
  eventPossession: (team, pos) => `Offense: ${team} (position ${pos})`,
  eventStallOut: (team, pos) => `Stall-out · turnover · ${team} · pos. ${pos}`,
  eventTurnover: (team, pos) => `Turnover · ${team} · position ${pos}`,
  eventScore: (team, reason) => `★ SCORE · ${team}${reason ? ` (${reason})` : ''}`,
  eventPointEnd: (throws) => `End of point · ${throws} throws`,
  eventInjury: (name, label, days) => `Injury · ${name} (${label}) · out ${days} days`,
  eventMatchEnd: (hs, as_, winner) => `Full time · ${hs}:${as_} · winner: ${winner}`,
  fullThrowLog: 'Full throw log',
  throwsN: (n) => `${n} throws`,
  historyBelow: 'history below',
  pointsEvents: (pts, ev) => `${pts} points · ${ev} events`,
  abbreviated: ' (abbreviated)',
  matchStatsTitle: 'Match statistics',
  homeShort: 'Home',
  awayShort: 'Away',
  yardsFromThrows: 'Yards from throws',
  completions: 'Completions',
  hucks: 'Hucks (≥40 m)',
  turnovers: 'Turnovers',
  hold: 'Hold',
  break: 'Break',
  huckTitle: 'Throw advancing the disc ≥ 40 m',
  holdTitle: 'Share of points held from your own offensive start',
  breakTitle: 'Share of points broken from your own defensive start',
  pressureCompletions: 'Under-pressure throws',
  pressureCompletionsTitle: 'Completion rate on throws released at a high stall count (under mark pressure)',
  pointHistoryTitle: 'Point history',
  pointHistorySubtitle: 'Full throw and turnover timeline',
  winnerLabel: 'winner',
  pointLabel: 'Point',
  personMatchups: (n) => `Person D · assignments (${n} pairs)`,
  possessionChange: (team, pos) => `Possession change → ${team} · pos. ${pos}`,
  personZoneFootnote: (zone) =>
    `Person: mark on receiver · Zone: ${zone} — pressure on the key player`,
  staminaPanelTitle: 'Point',
  staminaPanelHint: 'stamina · 7 on field',
  playerCol: 'Player',
  thrAbbr: 'THR',
  thrTitle: 'Throws (completions/attempts)',
  pctTitle: '% completions',
  tmTitle: 'Throwing meters',
  cmTitle: 'Catching meters',
  rmTitle: 'Running distance (m)',
  toTitle: 'Turnovers',
  blocksTitle: 'Blocks',
  assistTag: 'assist',
  goalTag: 'goal',
  statLegend: 'THR · % · Tm · Cm · Rm · TO · B',
  historyPointStart: (n, attack) => `Point start ${n} · offense: ${attack}`,
  boxScorersTitle: 'Match scorers',
  boxStatsTitle: 'Player stats summary',
  boxScorersSubtitle: 'Goals only (G) · full box score after the match',
  boxStatsSubtitle: 'Box Score · G / A / B (D-blocks) / TO / PP',
  boxScorersEmpty: 'No one has scored yet (G). Full stats appear after the match.',
  teamCol: 'Team',
  ppTitle: 'Points played',
  simTempo: 'Sim pace:',
  newMatch: 'New match',
  waitingAction: 'Waiting for action…',
  actionLabel: 'Action',
  phaseSetup: 'Setup',
  phaseThrow: 'Throw',
  phaseFlight: 'Flight',
  windLabel: (label) => `Wind ${label}`,
  attackShort: 'Offense',
  defenseShort: 'Defense',
  pointByPointMatch: 'Point-by-point match',
  matchLog: 'Match log',
  pointN: (n) => `Point ${n}:`,
  emptyField: 'No field data',
  discPossession: (meters, team) =>
    `Disc: ${meters} m · ${team} in possession`,
  matchupSubtitle: (homeName, homeCount, awayName, awayCount, pts) =>
    `${homeName} (${homeCount} players) vs ${awayName} (${awayCount} players) · to ${pts} pts`,
  seedOptional: 'Seed (optional)',
  seedRandomPlaceholder: 'random',
}

export function matchStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
