import { pickDict, UI_LANG } from '../locale'

const pl = {
  closeAria: 'Zamknij profil',
  close: 'Zamknij',
  age: 'Wiek',
  nationality: 'Narodowość',
  fatigue: 'Zmęcz. sezon',
  matchFreshness: 'Świeżość mecz.',
  injury: 'Kontuzja',
  days: (n) => (n === 1 ? 'dzień' : 'dni'),
  form: 'Forma',
  morale: 'Morale',
  dominant: 'Dominant',
  dominantRight: 'Praworęczny',
  dominantLeft: 'Leworęczny',
  marketValueTitle: 'Wartość rynkowa (OVR × wiek)',
  contractTitle: (wage, years, weeks) =>
    `Kontrakt: ${wage}/tydz. · ${years} lat · pozostało ${weeks} tyg.`,
  contractWeekShort: (wage, years) => `${wage}/t · ${years}l`,
  yearsShort: (years) => `${years}l`,
  contractSection: 'Kontrakt',
  weeklyWage: 'Tygodniówka',
  years: 'Lata',
  remaining: 'Pozostało',
  weeks: (n) => `${n} tyg.`,
  totalCost: 'Łączny koszt (reszta)',
  noContract: 'Brak kontraktu',
  extendContract: 'Przedłuż kontrakt',
  extending: 'Negocjacja…',
  extendWage: 'Nowa tygodniówka',
  extendYears: 'Lata',
  extendSubmit: 'Złóż ofertę',
  extendAccepted: 'Kontrakt przedłużony',
  extendRejected: 'Zawodnik odrzucił ofertę',
  startNegotiation: 'Rozpocznij negocjacje',
  addToTransferList: 'Wystaw na listę transferową',
  removeFromTransferList: 'Zdejmij z listy transferowej',
  transferListedBadge: 'Na liście transferowej',
  proposeLoanOut: 'Wypożycz',
  loanedOutBadge: (club, date) => `Wypożyczony do ${club} do ${date}`,
  loanedInBadge: (club, date) => `Wypożyczony od ${club} do ${date}`,
  traits: 'Cechy',
  season: 'Sezon bieżący',
  goals: 'Gole',
  assists: 'Asysty',
  blocks: 'Bloki',
  pointsPlayed: 'Punkty rozegrane',
  thisMatch: (n) => `w tym meczu: ${n}`,
  formTitle: (n) => `Forma ${n}/100`,
  moraleTitle: (n) => `Morale ${n}/100`,
  turnovers: 'Straty',
  plusMinus: 'Bilans (+/-)',
  completionPct: '% celnych podań',
  throwMeters: 'Metry rzucone',
  catchMeters: 'Metry złapane',
  avgPerAttempt: (n) => `śr. ${n} m/rzut`,
  avgPerCatch: (n) => `śr. ${n} m/łap.`,
  runDistance: 'Przebiegnięty dystans',
  noData: '—',
  growthTitle: 'Zmiana w ostatnich ~12 miesiącach',
}

const en = {
  closeAria: 'Close profile',
  close: 'Close',
  age: 'Age',
  nationality: 'Nationality',
  fatigue: 'Season fatigue',
  matchFreshness: 'Match freshness',
  injury: 'Injury',
  days: (n) => (n === 1 ? 'day' : 'days'),
  form: 'Form',
  morale: 'Morale',
  dominant: 'Dominant',
  dominantRight: 'Right-handed',
  dominantLeft: 'Left-handed',
  marketValueTitle: 'Market value (OVR × age)',
  contractTitle: (wage, years, weeks) =>
    `Contract: ${wage}/wk · ${years} yrs · ${weeks} wks left`,
  contractWeekShort: (wage, years) => `${wage}/w · ${years}y`,
  yearsShort: (years) => `${years}y`,
  contractSection: 'Contract',
  weeklyWage: 'Weekly wage',
  years: 'Years',
  remaining: 'Remaining',
  weeks: (n) => `${n} wks`,
  totalCost: 'Total cost (remaining)',
  noContract: 'No contract',
  extendContract: 'Extend contract',
  extending: 'Negotiating…',
  extendWage: 'New weekly wage',
  extendYears: 'Years',
  extendSubmit: 'Make offer',
  extendAccepted: 'Contract extended',
  extendRejected: 'Player rejected the offer',
  startNegotiation: 'Start negotiations',
  addToTransferList: 'Add to transfer list',
  removeFromTransferList: 'Remove from transfer list',
  transferListedBadge: 'Transfer listed',
  proposeLoanOut: 'Loan out',
  loanedOutBadge: (club, date) => `On loan at ${club} until ${date}`,
  loanedInBadge: (club, date) => `On loan from ${club} until ${date}`,
  traits: 'Traits',
  season: 'Current season',
  goals: 'Goals',
  assists: 'Assists',
  blocks: 'Blocks',
  pointsPlayed: 'Points played',
  thisMatch: (n) => `this match: ${n}`,
  formTitle: (n) => `Form ${n}/100`,
  moraleTitle: (n) => `Morale ${n}/100`,
  turnovers: 'Turnovers',
  plusMinus: 'Plus/minus (+/-)',
  completionPct: 'Pass completion %',
  throwMeters: 'Throwing meters',
  catchMeters: 'Receiving meters',
  avgPerAttempt: (n) => `avg ${n} m/throw`,
  avgPerCatch: (n) => `avg ${n} m/catch`,
  runDistance: 'Distance run',
  noData: '—',
  growthTitle: 'Change over the last ~12 months',
}

export function playerProfileStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
