import { pickDict, UI_LANG } from '../locale'

const MISSION_KIND_LABEL_PL = {
  tactics: 'Taktyka',
  keyPlayers: 'Kluczowi zawodnicy',
  player: 'Dossier zawodnika',
}

const MISSION_KIND_LABEL_EN = {
  tactics: 'Tactics',
  keyPlayers: 'Key players',
  player: 'Player dossier',
}

const pl = {
  sectionTitle: 'Scouting',
  knowledgeLabel: 'Znajomość drużyny',
  tacticsLabel: 'Znajomość taktyki',
  rosterOvrHeader: 'OVR',
  sendScoutButton: 'Wyślij skauta',
  dossierButton: 'Zleć dossier',
  missionKindLabel: (kind) => MISSION_KIND_LABEL_PL[kind] ?? kind,
  pickerTitle: 'Nowa misja skautingowa',
  pickerKindLabel: 'Typ misji',
  pickerPlayerLabel: 'Zawodnik',
  pickerPlayerPlaceholder: 'Wybierz zawodnika…',
  pickerCost: (costLabel) => `Koszt: ${costLabel}`,
  costLabel: 'Koszt misji',
  pickerCancel: 'Anuluj',
  pickerConfirm: 'Wyślij',
  pendingMissionsTitle: 'Misje w toku',
  pendingWaitingForMatch: 'Czeka na najbliższy mecz',
  pendingWaitingDossier: 'Dossier w przygotowaniu',
  noPendingMissions: 'Brak aktywnych misji skautingowych.',
  capacityLabel: (used, max) => `Sloty: ${used}/${max}`,
  errorCapacity: 'Brak wolnych slotów skautingu — rozbuduj dział skautingu albo poczekaj na zakończenie misji.',
  errorInsufficientFunds: 'Za mało środków w budżecie transferowym.',
  errorGeneric: 'Nie udało się wysłać skauta.',
  unknownHint: 'Brak informacji o tej drużynie — wyślij skauta, żeby to zmienić.',
  reportTacticsTag: 'Taktyka',
  reportKeyPlayersTag: 'Kluczowi zawodnicy',
  reportPlayerTag: 'Dossier',
  addToShortlist: 'Dodaj do shortlisty',
  removeFromShortlist: 'Usuń z shortlisty',
  scoutPlayerButton: 'Skautuj zawodnika',
  scoutPlayerPending: 'Skauting w toku…',
  scoutQueued: 'Skaut wysłany — raport trafi do skrzynki.',
  freeAgent: 'Wolny agent',
  centerTitle: 'Centrum skautingu',
  shortlistTitle: 'Shortlista',
  shortlistEmpty: 'Shortlista jest pusta — dodawaj zawodników z ich profilu (rynek transferowy, roster drużyny).',
  leagueTeamsTitle: 'Drużyny ligowe',
  colPlayer: 'Zawodnik',
  colTeam: 'Drużyna',
  colClub: 'Klub',
  colAge: 'Wiek',
  colKnowledge: 'Znajomość',
  colTactics: 'Taktyka',
  colOvr: 'OVR',
  colPending: 'Misje w toku',
  openProfile: 'Otwórz profil',
  scoutAction: 'Skautuj',
  removeAction: 'Usuń',
  scoutReportTitle: 'Raport skautingowy',
  bestSevenTitle: 'Najlepsza siódemka (statystyki sezonu)',
  expectedStyleTitle: 'Oczekiwany styl taktyczny',
  styleUnknownHint: 'Dokładny system nieznany — wyślij skauta, by go poznać.',
  tacticsKnowledgeLabel: 'Znajomość taktyki',
  forceLabel: 'Force',
}

const en = {
  sectionTitle: 'Scouting',
  knowledgeLabel: 'Team knowledge',
  tacticsLabel: 'Tactics knowledge',
  rosterOvrHeader: 'OVR',
  sendScoutButton: 'Send a scout',
  dossierButton: 'Commission dossier',
  missionKindLabel: (kind) => MISSION_KIND_LABEL_EN[kind] ?? kind,
  pickerTitle: 'New scouting mission',
  pickerKindLabel: 'Mission type',
  pickerPlayerLabel: 'Player',
  pickerPlayerPlaceholder: 'Choose a player…',
  pickerCost: (costLabel) => `Cost: ${costLabel}`,
  costLabel: 'Mission cost',
  pickerCancel: 'Cancel',
  pickerConfirm: 'Send',
  pendingMissionsTitle: 'Missions in progress',
  pendingWaitingForMatch: 'Waiting for their next match',
  pendingWaitingDossier: 'Dossier in progress',
  noPendingMissions: 'No active scouting missions.',
  capacityLabel: (used, max) => `Slots: ${used}/${max}`,
  errorCapacity: 'No free scouting slots — upgrade the scouting department or wait for a mission to finish.',
  errorInsufficientFunds: 'Not enough transfer budget.',
  errorGeneric: 'Could not send the scout.',
  unknownHint: 'No intel on this team yet — send a scout to change that.',
  reportTacticsTag: 'Tactics',
  reportKeyPlayersTag: 'Key players',
  reportPlayerTag: 'Dossier',
  addToShortlist: 'Add to shortlist',
  removeFromShortlist: 'Remove from shortlist',
  scoutPlayerButton: 'Scout this player',
  scoutPlayerPending: 'Scouting in progress…',
  scoutQueued: 'Scout sent — the report will land in your inbox.',
  freeAgent: 'Free agent',
  centerTitle: 'Scouting center',
  shortlistTitle: 'Shortlist',
  shortlistEmpty: 'Your shortlist is empty — add players from their profile (transfer market, team roster).',
  leagueTeamsTitle: 'League teams',
  colPlayer: 'Player',
  colTeam: 'Team',
  colClub: 'Club',
  colAge: 'Age',
  colKnowledge: 'Knowledge',
  colTactics: 'Tactics',
  colOvr: 'OVR',
  colPending: 'Missions in progress',
  openProfile: 'Open profile',
  scoutAction: 'Scout',
  removeAction: 'Remove',
  scoutReportTitle: 'Scouting report',
  bestSevenTitle: 'Best seven (season stats)',
  expectedStyleTitle: 'Expected tactical style',
  styleUnknownHint: 'Exact system unknown — send a scout to find out.',
  tacticsKnowledgeLabel: 'Tactics knowledge',
  forceLabel: 'Force',
}

export function scoutingStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
