import { pickDict, UI_LANG } from '../locale'

const pl = {
  appName: 'Ultimate Manager',
  loadingCareer: 'Ładowanie kariery…',
  saveAndExit: 'Zapisz i wróć do menu karier',
  navAria: 'Nawigacja główna',
  noActiveMatchTitle: 'Brak aktywnego meczu',
  noActiveMatchBody: 'Rozpocznij mecz z centrum lub terminarza drużyny.',
  goToHub: 'Centrum ligi',
  goToSchedule: 'Terminarz',
  goHome: 'Strona główna',
  teamSchedule: 'Terminarz drużyny',
  footer: (slot) => `Ultimate Manager · zapis ${slot} · autozapis w przeglądarce`,
  careerTitle: 'Profil kariery',
  careerMeta: (manager, team, seasonIndex, seasonLabel) =>
    `${manager} · ${team} · sezon #${seasonIndex} (${seasonLabel})`,
  seasonsDone: (n) => `Ukończone sezony: ${n}`,
  waitingNext: ' · czekasz na kolejny sezon',
  rosterAllTime: (n) => ` · skład: ${n} · all-time zapisane osobno od sezonu`,
  startNext: (label) => `Przejdź do ${label}`,
  seasonHistory: 'Historia sezonów',
  noSeasonsYet: 'Brak ukończonych sezonów — dokończ bieżący sezon.',
  cupWon: 'puchar',
  allTimeLeaders: 'Liderzy all-time (gole)',
  noAllTime: 'Brak statystyk all-time.',
  goals: (n) => `${n} goli`,
  simTeamTraining: 'Treningi drużynowe',
  simProcessingSessions: 'Przetwarzanie sesji…',
  simDay: (date) => `Dzień ${date}`,
  simFrom: (date) => `Od ${date}`,
  simDevelopment: 'Rozwój i regeneracja',
  simFatigue: 'Aktualizacja zmęczenia…',
  simUntilMatch: 'Symulacja do meczu',
  simCalendar: 'Symulacja kalendarza',
  simTransfersInbox: 'Transfery i skrzynka',
  simClosingDay: 'Domknięcie dnia…',
  simUntilDate: 'Symulacja do daty',
  simDone: 'Gotowe',
  errNoOffer: 'Brak oferty',
  errOfferNotFound: 'Nie znaleziono oferty transferowej',
  errOfferInactive: 'Ta oferta nie jest już aktywna',
}

const en = {
  appName: 'Ultimate Manager',
  loadingCareer: 'Loading career…',
  saveAndExit: 'Save and return to career menu',
  navAria: 'Main navigation',
  noActiveMatchTitle: 'No active match',
  noActiveMatchBody: 'Start a match from the hub or team schedule.',
  goToHub: 'League hub',
  goToSchedule: 'Schedule',
  goHome: 'Home',
  teamSchedule: 'Team schedule',
  footer: (slot) => `Ultimate Manager · slot ${slot} · autosave in browser`,
  careerTitle: 'Career profile',
  careerMeta: (manager, team, seasonIndex, seasonLabel) =>
    `${manager} · ${team} · season #${seasonIndex} (${seasonLabel})`,
  seasonsDone: (n) => `Seasons completed: ${n}`,
  waitingNext: ' · waiting for the next season',
  rosterAllTime: (n) => ` · roster: ${n} · all-time stored separately from the season`,
  startNext: (label) => `Continue to ${label}`,
  seasonHistory: 'Season history',
  noSeasonsYet: 'No completed seasons yet — finish the current one.',
  cupWon: 'cup',
  allTimeLeaders: 'All-time leaders (goals)',
  noAllTime: 'No all-time stats yet.',
  goals: (n) => `${n} goals`,
  simTeamTraining: 'Team training',
  simProcessingSessions: 'Processing sessions…',
  simDay: (date) => `Day ${date}`,
  simFrom: (date) => `From ${date}`,
  simDevelopment: 'Development & recovery',
  simFatigue: 'Updating fatigue…',
  simUntilMatch: 'Simulating until match',
  simCalendar: 'Calendar simulation',
  simTransfersInbox: 'Transfers & inbox',
  simClosingDay: 'Closing the day…',
  simUntilDate: 'Simulating until date',
  simDone: 'Done',
  errNoOffer: 'No offer',
  errOfferNotFound: 'Transfer offer not found',
  errOfferInactive: 'This offer is no longer active',
}

export function shellStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
