import { pickDict, UI_LANG } from '../locale'

const pl = {
  intro: 'Style O/D-Line, założenia trenera i instrukcje zawodników.',
  sevenNote: 'sama 7 gra cały punkt',
  seven: 'Siódemka',
  oLine: 'O-Line (domyślna siódemka)',
  dLine: 'D-Line (domyślna siódemka)',
  oLinePullHint: 'Gdy odbieracie pull — ta siódemka startuje punkt w ataku.',
  dLinePullHint: 'Gdy wykonujecie pull — ta siódemka startuje punkt w obronie.',
  startOffense: 'Zaczynasz w ataku',
  startDefense: 'Zaczynasz w obronie',
  startDefensePull: 'Zaczynasz w obronie',
  exhaustedWarn: 'Uwaga: wyczerpani zawodnicy w składzie (< 40% staminy)',
  exhaustedHint: 'Rozważ rotację — wyższe ryzyko turnoverów i gorsza obrona.',
  linked: 'Połączony',
  prepTitle: 'Przygotowanie meczu — taktyka i siódemki',
  finishMatch: 'Dokańcz mecz z tą taktyką',
  clearSlot: 'Wyczyść slot',
  pickPlayer: '— wybierz zawodnika —',
  pickBtn: 'Wybierz',
  openProfile: 'Otwórz profil',
  profile: 'Profil',
  noPlayersFilter: 'Brak zawodników dla tego filtra.',
  name: 'Imię',
  alreadyInSeven: 'Już w tej siódemce',
  hideOrders: 'Ukryj rozkazy',
  showOrders: 'Rozkazy',
  sortBy: 'Sortuj:',
  coachTitle: 'Założenia trenera',
  more: 'Więcej ▼',
  less: 'Mniej ▲',
  expand: 'Rozwiń ▼',
  coachNeutral: 'Neutralnie — bez silnych biasów.',
  coachHint: (line) =>
    `Wskazówki dla ${line} — posłuch zależy od cech i znajomości systemu.`,
  scales: 'Skale',
  change: 'Zmień ▼',
  collapse: 'Zwiń ▲',
  formationO: 'Podgląd formacji · O-Line',
  formationD: 'Podgląd formacji · D-Line',
  formationPreview: 'Podgląd formacji',
  formationPreviewHint: 'Układ startowy wg stylu ataku danej linii.',
  handlersCutters: (h, c) => `${h} handlerów / ${c} cutterów`,
  onField: (n) => `${n}/7 na boisku`,
  formationSlotHint: (h, c) =>
    `Formacja: ${h} handler${h === 1 ? '' : 'ów'} · ${c} cutter${c === 1 ? '' : 'ów'}. Kliknij pozycję, aby wstawić zawodnika z listy lub pełnego składu.`,
  noInstr: 'Brak — ustaw przy slocie na boisku („Rozkazy”) lub w pełnym składzie.',
  noTactics: 'Brak taktyki — wróć do kariery i spróbuj ponownie.',
  pointSeven: 'Siódemka na ten punkt',
  pointSevenHint: 'Ta sama 7 gra cały punkt w ataku i obronie.',
  lineStyles: 'Style linii',
  oLineStyles: 'Style O-Line',
  dLineStyles: 'Style D-Line',
  fullRoster: (name, n) => `Pełny skład · ${name} (${n})`,
  replaceHint: (label) =>
    `Wybrano ${label} — kliknij zawodnika poniżej, aby go wstawić.`,
  inLineup: 'w składzie',
  onLine: 'NA LINII',
  onLineSlot: (label) => `NA LINII · ${label}`,
  swapPositions: 'Zamień pozycje',
  dragToSwap: 'Przeciągnij, aby zamienić pozycje',
  shownOf: (a, b) => `Pokazano ${a} / ${b} · Wybierz = wstaw · Profil = karta`,
  allPlayers: 'Wszyscy',
  form: 'Forma',
  morale: 'Morale',
  pointLineupTitle: (n) => `Punkt ${n} — skład i taktyka`,
  instructions: 'Instrukcje',
  individualOrders: 'Rozkazy indywidualne',
  playersShort: (n) => `${n} zawodn.`,
  subRole: 'Podrola',
  subRoleTitle: 'Podrola w formacji',
  zoneRoles: 'Role w strefie',
  zoneRolesFor: (label) => `${label} · role w strefie`,
  zoneRolesHint: 'Kto gra w cupie, kto na wingu, middle i deep.',
  lineDotAttack: (label) => `${label} · atak`,
  lineDotDefense: (label) => `${label} · obrona`,
  lineDotStyles: (label) => `${label} · style`,
  attack: 'Atak',
  defense: 'Obrona',
  attackStyleOf: (prefix) => `${prefix} · styl ataku`,
  defenseStyleOf: (prefix) => `${prefix} · styl obrony`,
  formationAttackDefense: 'Formacja ataku i styl obrony.',
  formationAttackDefenseSeparate:
    'Formacja ataku i styl obrony osobno dla O-Line i D-Line.',
  tacticsViewAria: 'Widok taktyki',
  forceMark: 'Force (markowanie)',
  selected: 'wybrany',
  formationAria: (label) => `Formacja ${label}`,
  close: 'Zamknij',
}

const en = {
  intro: 'O/D-Line styles, coach directives and player instructions.',
  sevenNote: 'the same 7 plays the whole point',
  seven: 'Starting seven',
  oLine: 'O-Line (default seven)',
  dLine: 'D-Line (default seven)',
  oLinePullHint: 'When you receive the pull — this seven starts the point on offense.',
  dLinePullHint: 'When you pull — this seven starts the point on defense.',
  startOffense: 'You start on offense',
  startDefense: 'You start on defense',
  startDefensePull: 'You start on defense',
  exhaustedWarn: 'Warning: exhausted players in the lineup (< 40% stamina)',
  exhaustedHint: 'Consider rotation — higher turnover risk and weaker defense.',
  linked: 'Linked',
  prepTitle: 'Match prep — tactics and lineups',
  finishMatch: 'Finish the match with this tactics',
  clearSlot: 'Clear slot',
  pickPlayer: '— pick a player —',
  pickBtn: 'Pick',
  openProfile: 'Open profile',
  profile: 'Profile',
  noPlayersFilter: 'No players for this filter.',
  name: 'Name',
  alreadyInSeven: 'Already in this seven',
  hideOrders: 'Hide orders',
  showOrders: 'Orders',
  sortBy: 'Sort:',
  coachTitle: 'Coach directives',
  more: 'More ▼',
  less: 'Less ▲',
  expand: 'Expand ▼',
  coachNeutral: 'Neutral — no strong biases.',
  coachHint: (line) =>
    `Guidance for ${line} — buy-in depends on traits and system familiarity.`,
  scales: 'Scales',
  change: 'Change ▼',
  collapse: 'Collapse ▲',
  formationO: 'Formation preview · O-Line',
  formationD: 'Formation preview · D-Line',
  formationPreview: 'Formation preview',
  formationPreviewHint: 'Starting shape by that line’s attack style.',
  handlersCutters: (h, c) => `${h} handlers / ${c} cutters`,
  onField: (n) => `${n}/7 on field`,
  formationSlotHint: (h, c) =>
    `Formation: ${h} handler${h === 1 ? '' : 's'} · ${c} cutter${c === 1 ? '' : 's'}. Click a spot to insert a player from the list or full roster.`,
  noInstr: 'None — set at the on-field slot (“Orders”) or in the full roster.',
  noTactics: 'No tactics — return to career and try again.',
  pointSeven: 'Seven for this point',
  pointSevenHint: 'The same 7 plays the whole point on offense and defense.',
  lineStyles: 'Line styles',
  oLineStyles: 'O-Line styles',
  dLineStyles: 'D-Line styles',
  fullRoster: (name, n) => `Full roster · ${name} (${n})`,
  replaceHint: (label) => `Selected ${label} — click a player below to insert.`,
  inLineup: 'in lineup',
  onLine: 'ON LINE',
  onLineSlot: (label) => `ON LINE · ${label}`,
  swapPositions: 'Swap positions',
  dragToSwap: 'Drag to swap positions',
  shownOf: (a, b) => `Showing ${a} / ${b} · Pick = insert · Profile = card`,
  allPlayers: 'All',
  form: 'Form',
  morale: 'Morale',
  pointLineupTitle: (n) => `Point ${n} — lineup & tactics`,
  instructions: 'Instructions',
  individualOrders: 'Individual orders',
  playersShort: (n) => `${n} players`,
  subRole: 'Sub-role',
  subRoleTitle: 'Formation sub-role',
  zoneRoles: 'Zone roles',
  zoneRolesFor: (label) => `${label} · zone roles`,
  zoneRolesHint: 'Who plays cup, wing, middle, and deep.',
  lineDotAttack: (label) => `${label} · offense`,
  lineDotDefense: (label) => `${label} · defense`,
  lineDotStyles: (label) => `${label} · styles`,
  attack: 'Offense',
  defense: 'Defense',
  attackStyleOf: (prefix) => `${prefix} · attack style`,
  defenseStyleOf: (prefix) => `${prefix} · defense style`,
  formationAttackDefense: 'Attack formation and defense style.',
  formationAttackDefenseSeparate:
    'Attack formation and defense style separately for O-Line and D-Line.',
  tacticsViewAria: 'Tactics view',
  forceMark: 'Force mark',
  selected: 'selected',
  formationAria: (label) => `Formation ${label}`,
  close: 'Close',
}

export function tacticsStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
