import { pickDict, UI_LANG } from '../locale'

const pl = {
  notFound: 'Nie znaleziono drużyny.',
  back: 'Wróć',
  backArrow: '← Wróć',
  profileTitle: 'Profil drużyny',
  weekOf: (week, total) => `tydzień ${week}/${total}`,
  seasonFallback: 'Sezon',
  place: 'Miejsce',
  form: 'Forma',
  morale: 'Morale',
  reputation: 'Reputacja',
  fans: 'Kibice',
  fanMood: 'Nastrój trybun',
  clubPrestige: 'Prestiż klubu',
  prestigeHint: 'Kształtowana przez wyniki, transfery i decyzje klubowe',
  fanbase: 'Fanbase',
  mood: 'Nastrój',
  finances: 'Finanse',
  financesHint: 'Budżet transferowy, pensji i polityka klubu (modyfikator trudności negocjacji)',
  transferBudget: 'Budżet transferowy',
  wageBudget: 'Budżet pensji',
  rosterValue: 'Wartość kadry',
  transferPolicy: 'Polityka transferowa',
  negotiationDifficulty: 'Trudność negocjacji',
  bestSeven: 'Najlepsza siódemka',
  bestSevenHint: '7 zawodników o najwyższym OVR · statystyki sezonu',
  recentResults: 'Ostatnie wyniki',
  noPlayedMatches: 'Brak rozegranych meczów.',
  upcomingMatches: 'Nadchodzące mecze',
  noScheduled: 'Brak zaplanowanych spotkań.',
  weekShort: (n) => `Tydz. ${n}`,
  weekAbbrev: (n) => `W${n}`,
  scheduled: 'Zaplanowany',
  rosterStats: 'Kadra — statystyki sezonu',
  sortHint: 'Kliknij nagłówek kolumny, aby sortować',
  player: 'Zawodnik',
  hand: 'Ręka',
  traits: 'Cechy',
  goals: 'Gole',
  assists: 'Asysty',
  blocks: 'Bloki',
  pointsPlayed: 'Punkty rozegrane',
  teamOffense: 'Ofensywa',
  teamDefense: 'Defensywa',
  homeColor: 'Kolor domowy',
  awayColor: 'Kolor wyjazdowy',
  kitColors: 'Kolor domowy / wyjazdowy',
}

const en = {
  notFound: 'Team not found.',
  back: 'Back',
  backArrow: '← Back',
  profileTitle: 'Team profile',
  weekOf: (week, total) => `week ${week}/${total}`,
  seasonFallback: 'Season',
  place: 'Place',
  form: 'Form',
  morale: 'Morale',
  reputation: 'Reputation',
  fans: 'Fans',
  fanMood: 'Fan mood',
  clubPrestige: 'Club prestige',
  prestigeHint: 'Shaped by results, transfers and club decisions',
  fanbase: 'Fanbase',
  mood: 'Mood',
  finances: 'Finances',
  financesHint: 'Transfer budget, wages and club policy (negotiation difficulty modifier)',
  transferBudget: 'Transfer budget',
  wageBudget: 'Wage budget',
  rosterValue: 'Roster value',
  transferPolicy: 'Transfer policy',
  negotiationDifficulty: 'Negotiation difficulty',
  bestSeven: 'Best seven',
  bestSevenHint: '7 highest-OVR players · season stats',
  recentResults: 'Recent results',
  noPlayedMatches: 'No matches played yet.',
  upcomingMatches: 'Upcoming matches',
  noScheduled: 'No scheduled fixtures.',
  weekShort: (n) => `Wk ${n}`,
  weekAbbrev: (n) => `W${n}`,
  scheduled: 'Scheduled',
  rosterStats: 'Roster — season stats',
  sortHint: 'Click a column header to sort',
  player: 'Player',
  hand: 'Hand',
  traits: 'Traits',
  goals: 'Goals',
  assists: 'Assists',
  blocks: 'Blocks',
  pointsPlayed: 'Points played',
  teamOffense: 'Team offense',
  teamDefense: 'Team defense',
  homeColor: 'Home color',
  awayColor: 'Away color',
  kitColors: 'Home / away colors',
}

export function teamProfileStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
