import { pickDict, UI_LANG } from '../locale'

const pl = {
  title: 'Treningi drużynowe',
  intro:
    'Plan cotygodniowy i jednorazowy · fokusy A/B · intensywność wpływa na wzrost i zmęczenie.',
  tacticsFamiliarity: 'Znajomość taktyk',
  lastSession: 'Ostatnia sesja',
  attended: 'Obecnych',
  skillBumps: 'mikro-wzrostów skilli',
  tacticsPlus: 'taktyki',
  weekly: 'Cotygodniowy',
  weeklyHint: 'Powtarza się co tydzień w wybranym dniu',
  addWeekly: 'Dodaj',
  noWeekly: 'Brak zaplanowanych treningów tygodniowych.',
  oneOff: 'Jednorazowy',
  oneOffHint: 'Konkretna data w kalendarzu',
  scheduleOneOff: 'Zaplanuj',
  noOneOff: 'Brak zaplanowanych sesji jednorazowych.',
  remove: 'Usuń',
  enable: 'Włącz',
  disable: 'Wyłącz',
  errWeekly: 'Nie udało się dodać — wybierz dwa różne fokusy i wolny dzień tygodnia.',
  errOneOff: 'Nie udało się zaplanować jednorazowego treningu (data + 2 różne fokusy).',
  intensityHint:
    'Intensywność: lekka +mało zmęczenia / wysoka +więcej wzrostu i zmęczenia. Wzrost skilli jest celowo wolny — wiek i potencjał rozwoju limitują sufit.',
  individual: 'Trening indywidualny',
  individualHint: 'Dzienny fokus zawodnika (obok planu drużynowego).',
  filterAll: 'Wszyscy',
  filterYoung: 'Młodzi',
  filterVet: 'Weterani',
  filterTired: 'Zmęczeni',
  filterYoungFull: 'Młodzi (≤24)',
  filterVetFull: 'Weterani (30+)',
  individualTitle: (team) => `Fokus indywidualny · ${team}`,
  setAll: 'Ustaw wszystkim:',
  player: 'Zawodnik',
  age: 'Wiek',
  status: 'Status',
  trainingFocus: 'Fokus treningu',
  ready: 'Gotowy',
  done: 'odbyty',
  off: 'wyłączony',
  oneOffDateHint: 'Odbywa się tylko w wybranej dacie',
  noUpcomingOneOff: 'Brak nadchodzących sesji jednorazowych.',
  noTeam: 'Brak drużyny do treningu.',
  individualIntro:
    'Fokus nie jest osobnym treningiem — przyspiesza rozwój wybranych umiejętności na treningach drużynowych (i spowalnia pozostałe). Regeneracja obniża zmęczenie z sesji i szybciej regeneruje w dni bez treningu. Jedyny realny trening to sesje drużynowe.',
  fatigue: 'Zmęczenie',
  matchFreshness: 'Świeżość mecz.',
  attendance: 'frekwencja',
  engagement: 'zaangażowanie',
  luck: 'szczęście',
  selectAll: 'Zaznacz wszystkich',
  selectedCount: (n) => `Zaznaczono: ${n}`,
  applyToSelected: 'Zastosuj do zaznaczonych',
  clearSelection: 'Wyczyść zaznaczenie',
}

const en = {
  title: 'Team training',
  intro: 'Weekly and one-off plans · A/B focuses · intensity affects growth and fatigue.',
  tacticsFamiliarity: 'Tactics familiarity',
  lastSession: 'Last session',
  attended: 'Attended',
  skillBumps: 'micro skill bumps',
  tacticsPlus: 'tactics',
  weekly: 'Weekly',
  weeklyHint: 'Repeats every week on the chosen day',
  addWeekly: 'Add',
  noWeekly: 'No weekly trainings scheduled.',
  oneOff: 'One-off',
  oneOffHint: 'A specific date on the calendar',
  scheduleOneOff: 'Schedule',
  noOneOff: 'No one-off sessions scheduled.',
  remove: 'Remove',
  enable: 'Enable',
  disable: 'Disable',
  errWeekly: 'Could not add — pick two different focuses and a free weekday.',
  errOneOff: 'Could not schedule one-off training (date + 2 different focuses).',
  intensityHint:
    'Intensity: light = less fatigue / high = more growth and fatigue. Skill growth is intentionally slow — age and development room cap the ceiling.',
  individual: 'Individual training',
  individualHint: 'Daily player focus (alongside the team plan).',
  filterAll: 'All',
  filterYoung: 'Young',
  filterVet: 'Veterans',
  filterTired: 'Tired',
  filterYoungFull: 'Young (≤24)',
  filterVetFull: 'Veterans (30+)',
  individualTitle: (team) => `Individual focus · ${team}`,
  setAll: 'Set for all:',
  player: 'Player',
  age: 'Age',
  status: 'Status',
  trainingFocus: 'Training focus',
  ready: 'Ready',
  done: 'done',
  off: 'off',
  oneOffDateHint: 'Only on the selected date',
  noUpcomingOneOff: 'No upcoming one-off sessions.',
  noTeam: 'No team available for training.',
  individualIntro:
    'Focus is not a separate session — it speeds selected skills on team trainings (and slows the rest). Recovery lowers session fatigue and regenerates faster on off days. Real training is team sessions only.',
  fatigue: 'Fatigue',
  matchFreshness: 'Match freshness',
  attendance: 'attendance',
  engagement: 'engagement',
  luck: 'luck',
  selectAll: 'Select all',
  selectedCount: (n) => `Selected: ${n}`,
  applyToSelected: 'Apply to selected',
  clearSelection: 'Clear selection',
}

export function trainingStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
