import { pickDict, UI_LANG } from '../locale'

const pl = {
  title: 'Reprezentacje',
  intro:
    'Mistrzostwa Europy i Świata reprezentacji narodowych — kwalifikacje w przerwach na kadrę, faza finałowa w lipcu, na przemian co 2 lata.',
  tabs: {
    current: 'Aktualne rozgrywki',
    results: 'Wyniki',
    countries: 'Kraje',
    leaders: 'Klasyfikacja wszech czasów',
  },
  round: {
    champion: 'Mistrz',
    final: 'Finał',
    bronze: 'Brązowy medal',
    fourth: '4. miejsce',
    semifinal: 'Półfinał',
    quarterfinal: 'Ćwierćfinał',
    roundOf16: '1/8 finału',
    group: 'Faza grupowa',
  },
  bronzeMatch: 'Mecz o 3. miejsce',
  bronzeBanner: (name) => `Brązowy medal: ${name}`,
  kind: {
    euro: 'Mistrzostwa Europy',
    world: 'Mistrzostwa Świata',
  },
  kindShort: {
    euro: 'ME',
    world: 'MŚ',
  },
  waiting: 'TBD',
  // -- Twoi zawodnicy w kadrach --
  yourPlayersTitle: 'Twoi zawodnicy w kadrach',
  yourPlayersEmpty: 'Żaden zawodnik Twojego klubu nie został obecnie powołany do kadry narodowej.',
  yourPlayersProvisional: 'Kadry nie są jeszcze ogłoszone — poniżej zawodnicy uprawnieni do powołania.',
  nextFixture: (date) => `następny mecz: ${date}`,
  noFixtureScheduled: 'brak zaplanowanego meczu',
  // -- Current competition --
  emptyWindowTitle: 'Między turniejami',
  emptyWindowBody: (kind, year) =>
    `Kwalifikacje do ${kind} ${year} ruszą wraz z kolejną przerwą reprezentacyjną.`,
  firstCycleNote: 'Pierwszy cykl (ME 2027) rusza bez kwalifikacji — uczestnicy dobrani wprost wg rankingu.',
  qualifyingTitle: (kind, year) => `Kwalifikacje: ${kind} ${year}`,
  finalsTitle: (kind, year) => `Faza finałowa: ${kind} ${year}`,
  zoneAutoQualified: 'Awans automatyczny (za mało krajów w strefie)',
  phaseGroupStage: 'Faza grupowa',
  phasePlayoff: 'Baraże',
  phaseKnockout: 'Faza pucharowa',
  phaseComplete: 'Zakończone',
  groupLabel: (id) => `Grupa ${id.replace('group-', '')}`,
  standingsHeaders: { team: 'Kraj', w: 'Z', l: 'P', pf: 'PZ', pa: 'PS', diff: 'Bil.' },
  playoffTitle: 'Baraże',
  bracketTitle: 'Drabinka pucharowa',
  championBanner: (name) => `Mistrz: ${name}`,
  // -- Countries --
  countriesIntro: 'Wybierz kraj, żeby zobaczyć jego profil reprezentacyjny.',
  backToCountries: '← Wróć do listy krajów',
  tier: 'Ranking światowy',
  currentSquad: 'Aktualna/ostatnia kadra',
  noSquad: 'Ta kadra nie została jeszcze nigdy ogłoszona.',
  squadAsOf: (year) => `stan na: ${year}`,
  topPlayersTitle: 'Najlepsi zawodnicy tej narodowości',
  noTopPlayers: 'Brak zawodników tej narodowości w bazie świata.',
  trophyCabinetReal: 'Przed Twoją karierą',
  trophyCabinetCareer: 'W Twojej karierze',
  noTrophies: 'Brak medali w tym oknie.',
  medalGold: 'złoto',
  medalSilver: 'srebro',
  medalSemifinal: 'półfinał',
  // -- Results --
  resultsEmpty: 'Żaden turniej reprezentacji nie został jeszcze rozegrany w tej karierze.',
  resultsFilterAll: 'Wszystkie',
  finalScore: 'Wynik finału',
  groupTable: 'Tabela grupowa',
  pickResult: 'Wybierz turniej z listy.',
  // -- Leaders --
  leadersHint: 'Skumulowane statystyki ze wszystkich rozegranych turniejów reprezentacji w tej karierze.',
  leadersEmpty: 'Brak danych — żaden turniej nie został jeszcze rozegrany.',
  goals: 'Gole',
  assists: 'Asysty',
  blocks: 'Bloki',
  turnovers: 'Straty',
  noData: '—',
}

const en = {
  title: 'International',
  intro:
    'Euro and World Championships for national teams — qualifying during international breaks, finals every July, alternating every 2 years.',
  tabs: {
    current: 'Current competition',
    results: 'Results',
    countries: 'Countries',
    leaders: 'All-time leaders',
  },
  round: {
    champion: 'Champion',
    final: 'Final',
    bronze: 'Bronze medal',
    fourth: '4th place',
    semifinal: 'Semifinal',
    quarterfinal: 'Quarterfinal',
    roundOf16: 'Round of 16',
    group: 'Group stage',
  },
  bronzeMatch: 'Bronze medal match',
  bronzeBanner: (name) => `Bronze medal: ${name}`,
  kind: {
    euro: 'European Championship',
    world: 'World Championship',
  },
  kindShort: {
    euro: 'Euro',
    world: 'World',
  },
  waiting: 'TBD',
  yourPlayersTitle: 'Your players on national duty',
  yourPlayersEmpty: 'None of your club players are currently called up to a national team.',
  yourPlayersProvisional: 'Squads have not been announced yet — these players are eligible for a call-up.',
  nextFixture: (date) => `next match: ${date}`,
  noFixtureScheduled: 'no match scheduled',
  emptyWindowTitle: 'Between tournaments',
  emptyWindowBody: (kind, year) =>
    `Qualifying for ${kind} ${year} will start with the next international break.`,
  firstCycleNote: 'The first cycle (Euro 2027) starts without qualifying — participants are picked directly by ranking.',
  qualifyingTitle: (kind, year) => `Qualifying: ${kind} ${year}`,
  finalsTitle: (kind, year) => `Finals: ${kind} ${year}`,
  zoneAutoQualified: 'Auto-qualified (too few countries in this zone)',
  phaseGroupStage: 'Group stage',
  phasePlayoff: 'Playoff',
  phaseKnockout: 'Knockout stage',
  phaseComplete: 'Complete',
  groupLabel: (id) => `Group ${id.replace('group-', '')}`,
  standingsHeaders: { team: 'Country', w: 'W', l: 'L', pf: 'PF', pa: 'PA', diff: 'Diff' },
  playoffTitle: 'Playoff',
  bracketTitle: 'Knockout bracket',
  championBanner: (name) => `Champion: ${name}`,
  countriesIntro: 'Pick a country to see its national team profile.',
  backToCountries: '← Back to countries',
  tier: 'World ranking',
  currentSquad: 'Current / last squad',
  noSquad: 'This squad has never been announced yet.',
  squadAsOf: (year) => `as of: ${year}`,
  topPlayersTitle: 'Top players of this nationality',
  noTopPlayers: 'No players of this nationality in the world database.',
  trophyCabinetReal: 'Before your career',
  trophyCabinetCareer: 'In your career',
  noTrophies: 'No medals in this window.',
  medalGold: 'gold',
  medalSilver: 'silver',
  medalSemifinal: 'semifinal',
  resultsEmpty: 'No national team tournament has been played yet in this career.',
  resultsFilterAll: 'All',
  finalScore: 'Final score',
  groupTable: 'Group table',
  pickResult: 'Pick a tournament from the list.',
  leadersHint: 'Cumulative stats from every national team tournament played in this career.',
  leadersEmpty: 'No data yet — no tournament has been played.',
  goals: 'Goals',
  assists: 'Assists',
  blocks: 'Blocks',
  turnovers: 'Turnovers',
  noData: '—',
}

export function internationalCompetitionStrings(lang = UI_LANG.PL) {
  return pickDict({ pl, en }, lang)
}
