import { useState } from 'react'
import { ensureClubStaff, STAFF_ROLE_DEFS, staffMarket, hireClubStaff, releaseClubStaff, renewClubStaff, staffPayroll, staffReleaseCost, STAFF_SPECIALTY_LABELS } from '../career/clubStaff.js'
import { ensureClubManagement, buildSquadPlan } from '../career/clubManagement.js'

import { formatUsd } from '../career/transfers/moneyFormat.js'
const inputClass='rounded-md border border-ufa-border bg-ufa-bg p-2 text-sm'
export default function StaffManagementPanel({team,lang,onChange,currentDate}) {
  const en=lang==='en',members=ensureClubStaff(team),date=currentDate??team.managementDate??`${team.financeSeasonYear??2025}-08-01`
  const [role,setRole]=useState('assistantCoach'),[years,setYears]=useState(1),[error,setError]=useState('')
  function act(fn) { const result=fn();setError(result.ok?'':result.error==='insufficient_funds'?(en?'Insufficient available funds.':'Brak dostępnych środków.'):(en?'Offer unavailable.':'Oferta niedostępna.'));if(result.ok){ensureClubManagement(team,team.financeSeasonYear);onChange?.()} }
  const labels={coaching:['Szkolenie','Coaching'],development:['Rozwój','Development'],communication:['Komunikacja','Communication'],judgement:['Ocena','Judgement'],network:['Kontakty','Network'],recovery:['Regeneracja','Recovery'],prevention:['Profilaktyka','Prevention'],negotiation:['Negocjacje','Negotiation'],planning:['Planowanie','Planning'],analysis:['Analiza','Analysis']}
  return <section className="space-y-3"><h2 className="text-2xl font-semibold text-ufa-text">{en?'Club staff':'Sztab klubowy'}</h2><p className="text-sm text-ufa-muted">{en?'Weekly payroll':'Pensje tygodniowo'}: {formatUsd(staffPayroll(team))}</p>
    {error&&<p role="alert" className="text-ufa-danger">{error}</p>}
    <div className="grid gap-3 md:grid-cols-2">{Object.entries(STAFF_ROLE_DEFS).map(([id,def])=>{const p=members[id];return <article key={id} className="rounded-md border border-ufa-border p-3"><h4 className="font-semibold">{def[en?'en':'pl']}</h4>{p?<><p>{p.name} · {p.age}</p><p className="text-xs text-ufa-muted">{Object.entries(p.skills).map(([s,v])=>`${labels[s]?.[en?1:0]??s} ${v}/20`).join(' · ')}</p><p className="text-sm">{STAFF_SPECIALTY_LABELS[p.specialty]?.[en?1:0]??p.specialty} · {formatUsd(p.weeklyWage)}/{en?'week':'tydz.'}</p><p className="text-xs">{en?'Contract until':'Umowa do'} {p.expiresOn}</p><div className="mt-2 flex flex-wrap gap-2"><button className={inputClass} onClick={()=>act(()=>renewClubStaff(team,id,date,years))}>{en?'Extend':'Przedłuż'} +{years} {en?'yr':years===1?'rok':'lata'}</button><button className={inputClass} onClick={()=>act(()=>releaseClubStaff(team,id,date))}>{en?'Release':'Zwolnij'} · {formatUsd(staffReleaseCost(p,date))}</button></div></>:<p className="text-ufa-muted">{en?'Vacant':'Wakat'}</p>}</article>})}</div>
    {members.sportingDirector&&<p className="text-sm">{en?'Director’s squad review — missing handlers / cutters':'Przegląd kadry dyrektora — braki: handlerzy / cutterzy'}: {buildSquadPlan(team).needs.handler} / {buildSquadPlan(team).needs.cutter}</p>}
    <details><summary className="font-semibold">{en?'Recruitment market':'Rynek sztabu'}</summary><div className="my-3 flex flex-wrap gap-2"><select aria-label={en?'Role':'Stanowisko'} className={inputClass} value={role} onChange={e=>setRole(e.target.value)}>{Object.entries(STAFF_ROLE_DEFS).map(([id,d])=><option key={id} value={id}>{d[en?'en':'pl']}</option>)}</select><label>{en?'Contract years ':'Długość umowy '}<select className={inputClass} value={years} onChange={e=>setYears(Number(e.target.value))}>{[1,2,3].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><p className="text-xs text-ufa-muted">{en?'Hiring costs four weekly wages plus the incumbent’s severance. Offers refresh monthly.':'Zatrudnienie kosztuje cztery tygodnie pensji oraz odprawę obecnego pracownika. Oferty odświeżają się co miesiąc.'}</p>{staffMarket(team,role,date).map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-ufa-border py-3"><div><p>{p.name} · {en?'Level':'Poziom'} {p.level}</p><p className="text-xs">{formatUsd(p.weeklyWage)}/{en?'week':'tydz.'} · {STAFF_SPECIALTY_LABELS[p.specialty]?.[en?1:0]??p.specialty}</p></div><button disabled={!p.interested||members[role]?.id===p.id} className={`${inputClass} disabled:opacity-40`} onClick={()=>act(()=>hireClubStaff(team,role,p.id,date,years))}>{p.interested?(en?'Hire':'Zatrudnij'):(en?'Higher reputation required':'Wymagana wyższa reputacja')} · {formatUsd(p.weeklyWage*4+staffReleaseCost(members[role],date))}</button></div>)}</details>
  </section>
}
