import { useState } from 'react'
import { useUiLang } from '../ui/UiLangContext'
import { CLUB_TRACKS, STAFF_FUNCTIONS, clubTrackQuote, upgradeClubTrack } from '../career/streamlinedClub.js'
import { clubBudgetAllocation, clubFinanceForecast } from '../career/clubEconomy.js'
import { clubObjectives } from '../career/clubObjectives.js'
import { ensureClubStaff, staffMarket, staffPayroll, staffReleaseCost, hireClubStaff, STAFF_SPECIALTY_LABELS } from '../career/clubStaff.js'
import { facilityEffectSummary, facilityName } from '../career/clubFacilities.js'
import { formatUsd } from '../career/transfers/moneyFormat.js'

export function StreamlinedFinanceSummary({ team, lang = 'pl' }) {
  const en = lang === 'en', budget = clubBudgetAllocation(team), forecast = clubFinanceForecast(team)
  const values = [[en ? 'Cash' : 'Gotówka', budget.cash], [en ? 'Contract obligations' : 'Zobowiązania kontraktowe', forecast.commitments], [en ? 'Reserved now' : 'Odłożona rezerwa', budget.automaticReserve ?? budget.seasonPayrollBudget], [en ? 'Available for decisions' : 'Dostępne na decyzje', budget.transferBudget]]
  return <div className="space-y-2"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{values.map(([label, amount]) => <div key={label} className="rounded border border-ufa-border p-3"><p className="text-xs text-ufa-muted">{label}</p><strong>{formatUsd(amount)}</strong></div>)}</div><p className="text-xs text-ufa-muted">{team.streamlinedClub?.economyActive ? (en ? 'Reserve: player wages through season end + eight weeks of operations. It adjusts automatically. Obligations include future seasons and are not charged again now.' : 'Rezerwa: pensje zawodników do końca sezonu + osiem tygodni utrzymania. Aktualizuje się automatycznie. Zobowiązania obejmują przyszłe sezony; nie pobieramy ich ponownie teraz.') : (en ? 'Existing budget rules remain until the next season; automatic reserves start then.' : 'Do końca tego sezonu obowiązuje dotychczasowy podział budżetu. Automatyczna rezerwa ruszy w kolejnym sezonie.')}</p></div>
}
export default function StreamlinedClubView({ career, onChange, section = 'board' }) {
  const { lang } = useUiLang(), en = lang === 'en', team = career.world.teamsById[career.playerTeamId], date = career.league.currentDate
  const [flash, setFlash] = useState(''), [cap, setCap] = useState(team.streamlinedClub.staffRenewalCap ?? staffPayroll(team))
  const staff = ensureClubStaff(team), project = team.streamlinedClub.project ?? team.facilityProject
  const run = action => { const r = action(); setFlash(r.ok ? (en ? 'Decision saved.' : 'Decyzja zapisana.') : ({ insufficient_funds: en ? 'Insufficient available funds.' : 'Za mało dostępnych środków.', construction_in_progress: en ? 'Complete the current project first.' : 'Najpierw ukończ bieżącą budowę.' }[r.error] ?? r.error)); if (r.ok) onChange?.() }
  return <section className="um-section space-y-4">
    <h2 className="text-2xl font-semibold">{section === 'staff' ? (en ? 'Three staff functions' : 'Trzy funkcje sztabu') : (en ? 'Club priorities' : 'Priorytety klubu')}</h2>
    <StreamlinedFinanceSummary team={team} lang={lang} />
    {career.streamlinedMigration && <details><summary>{en ? 'Version migration summary' : 'Podsumowanie zmiany wersji'}</summary><p className="mt-2 text-sm">{career.streamlinedMigration[en ? 'messageEn' : 'messagePl']}</p></details>}
    {flash && <p role="status">{flash}</p>}
    {section === 'board' ? <>
      <div className="grid gap-3 md:grid-cols-3">{clubObjectives(team, lang).slice(0, 3).map((goal, i) => <div key={goal.id} className="rounded border border-ufa-border p-3"><p className="text-xs text-ufa-muted">{i === 0 ? (en ? 'Primary goal' : 'Cel główny') : (en ? 'Secondary goal' : 'Cel dodatkowy')}</p><strong>{goal.label}: {goal.target}</strong><p className="text-xs">{goal.deadline}</p></div>)}</div>
      {project && <p className="rounded border border-ufa-gold p-3">{en ? 'Paid construction in progress; completion' : 'Opłacona budowa w toku; ukończenie'}: {project.completesOn}</p>}
      <div className="grid gap-3 lg:grid-cols-3">{Object.entries(CLUB_TRACKS).map(([id, track]) => {
        const quote = clubTrackQuote(team, id)
        return <article key={id} className="space-y-3 rounded border border-ufa-border p-4"><h3 className="font-semibold">{track[en ? 'en' : 'pl']} · {quote.tier}/3</h3><p className="text-sm">{track[en ? 'effectEn' : 'effectPl']}</p>{quote.target ? <><p className="text-sm">{en ? 'Now' : 'Teraz'}: {formatUsd(quote.cost)}<br />{en ? 'Weekly upkeep change' : 'Zmiana utrzymania / tydzień'}: +{formatUsd(quote.upkeepDelta)}<br />{en ? 'Remaining after reserve' : 'Zostanie po rezerwie'}: {formatUsd(quote.remaining)}<br />{quote.days} {en ? 'days' : 'dni'}</p><button className="um-button" disabled={!!project || quote.remaining < 0} onClick={() => run(() => upgradeClubTrack(team, id, date))}>{en ? 'Invest' : 'Zainwestuj'}</button></> : <p>{en ? 'Fully developed' : 'Pełna rozbudowa'}</p>}<details><summary className="text-xs">{en ? 'Effects & preserved assets' : 'Efekty i zachowane obiekty'}</summary>{track.facilities.map(f => <p key={f} className="mt-2 text-xs">{facilityName(f, lang)} · {quote.levels[f]} → {quote.targets[f] ?? quote.levels[f]}: {facilityEffectSummary(f, quote.targets[f] ?? quote.levels[f], lang)}</p>)}</details></article>
      })}</div>
    </> : <>
      <div className="space-y-2 rounded border border-ufa-border p-3"><label>{en ? 'Approved total weekly payroll for automatic renewals' : 'Zatwierdzony łączny koszt sztabu / tydzień przy automatycznym odnowieniu'} <input aria-label={en ? 'Renewal payroll limit' : 'Limit odnowień'} className="rounded border border-ufa-border bg-ufa-bg p-2" type="number" min="0" value={cap} onChange={e => setCap(Number(e.target.value))} /></label><div className="flex gap-2"><button className="um-button" disabled={!Number.isFinite(cap) || cap < 0} onClick={() => { team.streamlinedClub.staffRenewalCap = cap; onChange?.(); setFlash(en ? 'Renewal limit approved.' : 'Zatwierdzono limit odnowień.') }}>{en ? 'Approve limit' : 'Zatwierdź limit'}</button><button className="um-button" onClick={() => { team.streamlinedClub.staffRenewalCap = null; onChange?.() }}>{en ? 'Disable automatic renewals' : 'Wyłącz automatyczne odnowienia'}</button></div><p className="text-xs text-ufa-muted">{en ? 'Only the three lead roles renew automatically, for one year at the same wage, within the approved payroll limit and available cash. Existing support contracts run to expiry.' : 'Automatycznie odnawiają się trzy główne funkcje, na rok i z tą samą pensją, w zatwierdzonym limicie całego sztabu i przy dostępnych środkach. Dotychczasowe umowy pomocnicze trwają do wygaśnięcia.'}</p><p>{en ? 'Active limit' : 'Aktywny limit'}: {team.streamlinedClub.staffRenewalCap == null ? '—' : formatUsd(team.streamlinedClub.staffRenewalCap)}</p></div>
      <div className="grid gap-3 lg:grid-cols-3">{STAFF_FUNCTIONS.map(group => <article key={group.id} className="space-y-3 rounded border border-ufa-border p-4"><h3 className="text-xl font-semibold">{group[en ? 'en' : 'pl']}</h3>{group.roles.filter(r => staff[r]).map(r => <p key={r} className="text-sm">{staff[r].name} · {staff[r].level}/3 · {STAFF_SPECIALTY_LABELS[staff[r].specialty]?.[en ? 1 : 0] ?? staff[r].specialty}<br />{formatUsd(staff[r].weeklyWage)}/{en ? 'wk' : 'tydz.'} · {staff[r].expiresOn}</p>)}
        <details><summary>{en ? 'Hire / replace lead' : 'Zatrudnij / zmień prowadzącego'}</summary>{staffMarket(team, group.primary, date).map(candidate => { const now = candidate.weeklyWage * 4 + staffReleaseCost(staff[group.primary], date), delta = candidate.weeklyWage - (staff[group.primary]?.weeklyWage ?? 0), remaining = clubBudgetAllocation(team).transferBudget - now - (team.streamlinedClub.economyActive ? Math.max(0, delta) * 8 : 0); return <div key={candidate.id} className="mt-3 space-y-1 border-t border-ufa-border pt-2"><strong>{candidate.name} · {candidate.level}/3</strong><p className="text-xs">{STAFF_SPECIALTY_LABELS[candidate.specialty]?.[en ? 1 : 0] ?? candidate.specialty} · {formatUsd(candidate.weeklyWage)}/{en ? 'wk' : 'tydz.'}</p><p className="text-xs">{en ? 'Now / weekly change / remaining' : 'Teraz / zmiana tygodniowo / zostanie'}: {formatUsd(now)} / {formatUsd(delta)} / {formatUsd(remaining)}</p><button className="um-button" disabled={!candidate.interested || remaining < 0 || staff[group.primary]?.id === candidate.id} onClick={() => run(() => hireClubStaff(team, group.primary, candidate.id, date))}>{en ? 'Hire for one year' : 'Zatrudnij na rok'}</button></div> })}</details>
      </article>)}</div>
    </>}
  </section>
}
