import { useState } from 'react'
import { useUiLang } from '../ui/UiLangContext'
import { getPlayerFullName } from '../data/mockPlayers.js'
import { currentMatchStamina } from '../matchEngine/stamina.js'
import { workloadRisk, trainingParticipation } from '../models/playerWorkload.js'
import { SESSION_DEFS, TRAINING_TEMPLATES, ensureTrainingSchedule, setTrainingTemplate, setTrainingSlot, resolveTrainingDay, trainingDateAdd, trainingFixtures, forecastTrainingPlayer } from '../career/trainingSchedule.js'

const inputClass='rounded-md border border-ufa-border bg-ufa-bg p-2 text-sm text-ufa-text disabled:opacity-40'
const reasons={ match:['Występ meczowy','Match duty'],rest:['Odpoczynek','Rest'],rehab:['Rehabilitacja','Rehabilitation'],overload:['Odciążenie: zmęczenie','Rest: overload'],return:['Powrót po urazie','Return from injury'],normal:['Pełny trening','Full training'] }
export default function TrainingSchedulePanel({team,league,disabled,onChange}) {
  const {lang}=useUiLang(),en=lang==='en'
  const today=league?.currentDate
  const [offset,setOffset]=useState(0)
  const s=ensureTrainingSchedule(team)
  if(!today)return null
  s.fixtureCache=trainingFixtures(league,team.id).map(f=>({date:f.date}))
  const start=trainingDateAdd(today,offset),dates=Array.from({length:7},(_,i)=>trainingDateAdd(start,i))
  const change=()=>onChange?.(team)
  const fixtures=trainingFixtures(league,team.id).filter(f=>f.date>=today).sort((a,b)=>a.date.localeCompare(b.date))
  const next=fixtures[0]?.date??trainingDateAdd(today,7)
  const riskLabels={normal:en?'Normal':'Normalne',raised:en?'Raised':'Podwyższone',high:en?'High':'Wysokie'}
  const warnings=dates.flatMap(date=>{
    const plans=resolveTrainingDay(team,date,league)??[],load=plans.reduce((sum,p)=>sum+(p.load??0),0)
    return load>=24?[`${date}: ${en?'Heavy training day. Consider reducing a session.':'Duże obciążenie dnia. Rozważ zmniejszenie liczby sesji.'}`]:plans.some(p=>p.reason==='preMatch'&&(p.load??0)>=12)?[`${date}: ${en?'Heavy session before a match.':'Ciężka sesja przed meczem.'}`]:[]
  })
  return <section className="space-y-4 rounded-md border border-ufa-border bg-ufa-panel p-4">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3>{en?'Training schedule':'Harmonogram treningów'}</h3><p className="text-sm text-ufa-muted">{en?'Regular sessions, individual load and daily recovery.':'Regularne sesje, indywidualne obciążenie i codzienna regeneracja.'}</p></div><div className="flex gap-2"><button className={inputClass} disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-7))}>←</button><span className="self-center text-sm">{start}</span><button className={inputClass} disabled={offset>=21} onClick={()=>setOffset(offset+7)}>→</button></div></div>
    <fieldset disabled={disabled} className="flex flex-wrap items-center gap-3">
      <label className="text-sm">{en?'Repeating plan ':'Plan powtarzalny '}<select className={inputClass} value={s.legacy?'legacy':s.template} onChange={e=>{setTrainingTemplate(team,e.target.value);change()}}>{s.legacy&&<option value="legacy">{en?'Existing saved plan':'Dotychczasowy zapisany plan'}</option>}{Object.entries(TRAINING_TEMPLATES).map(([id,d])=><option key={id} value={id}>{d[en?'en':'pl']}</option>)}</select></label>
      <label className="text-sm"><input type="checkbox" checked={s.adaptMatches} onChange={e=>{s.adaptMatches=e.target.checked;change()}}/> {en?'Adapt to fixtures':'Dostosuj do meczów'}</label>
      <label className="text-sm"><input type="checkbox" checked={s.autoRest} onChange={e=>{s.autoRest=e.target.checked;change()}}/> {en?'Automatic individual rest':'Automatyczny odpoczynek indywidualny'}</label>
      <label className="text-sm"><input type="checkbox" disabled={disabled||!team.staff?.assistantCoach} checked={s.delegated} onChange={e=>{s.delegated=e.target.checked;change()}}/> {en?'Delegate to assistant':'Deleguj asystentowi'}{!team.staff?.assistantCoach&&<span className="text-ufa-muted"> {en?'(vacant)':'(wakat)'}</span>}</label>
      <label className="text-sm">{en?'Rest below freshness ':'Odpoczynek poniżej świeżości '}<select className={inputClass} value={s.restBelow} onChange={e=>{s.restBelow=Number(e.target.value);change()}}>{[45,55,65,75].map(n=><option key={n}>{n}</option>)}</select></label>
    </fieldset>
    {warnings.length>0&&<ul className="space-y-1 text-sm text-ufa-gold">{warnings.map(w=><li key={w}>{w}</li>)}</ul>}
    {s.legacy?<p className="text-sm text-ufa-muted">{en?'Your existing sessions are preserved below. Choose a repeating plan to activate the new calendar.':'Dotychczasowe sesje są zachowane poniżej. Wybierz plan powtarzalny, aby uruchomić nowy kalendarz.'}</p>:<>
      <label className="block text-sm">{en?'Template for the displayed calendar week ':'Szablon tygodnia kalendarzowego obejmującego pierwszą datę '}<select disabled={disabled} className={inputClass} value={s.weeks[trainingDateAdd(start,-((new Date(`${start}T12:00:00`).getDay()+6)%7))]??''} onChange={e=>{const monday=trainingDateAdd(start,-((new Date(`${start}T12:00:00`).getDay()+6)%7));if(e.target.value)setTrainingTemplate(team,e.target.value,monday);else delete s.weeks[monday];change()}}><option value="">{en?'Use repeating plan':'Plan powtarzalny'}</option>{Object.entries(TRAINING_TEMPLATES).map(([id,d])=><option key={id} value={id}>{d[en?'en':'pl']}</option>)}</select></label>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{dates.map(d=><th className="min-w-44 border-b border-ufa-border p-2 text-left" key={d}>{new Date(`${d}T12:00:00`).toLocaleDateString(en?'en-GB':'pl-PL',{weekday:'short',day:'numeric',month:'short'})}</th>)}</tr></thead><tbody>{[0,1,2].map(slot=><tr key={slot}>{dates.map(date=>{
        const plan=resolveTrainingDay(team,date,league)?.find(p=>p.slot===slot),match=resolveTrainingDay(team,date,league)?.[0]?.type==='match'
        return <td key={date} className="border-b border-ufa-border p-2 align-top"><p className="mb-1 text-xs text-ufa-muted">{slot===2?(en?'Additional':'Dodatkowy'):`${en?'Session':'Sesja'} ${slot+1}`}</p>{match?<span>{slot===0?(en?'Match — training blocked':'Mecz — trening zablokowany'):'—'}</span>:<><select aria-label={`${date} ${slot+1}`} disabled={disabled} className={`${inputClass} w-full`} value={plan?.type??'rest'} onChange={e=>{setTrainingSlot(team,date,slot,e.target.value,plan?.group);change()}}>{Object.entries(SESSION_DEFS).filter(([id])=>id!=='match').map(([id,d])=><option key={id} value={id}>{d[en?'en':'pl']}</option>)}</select><select aria-label={en?'Training group':'Grupa treningowa'} disabled={disabled} className={`${inputClass} mt-1 w-full`} value={plan?.group??'all'} onChange={e=>{setTrainingSlot(team,date,slot,plan?.type??'rest',e.target.value);change()}}>{[['all','Wszyscy','Everyone'],['handlers','Handlerzy','Handlers'],['cutters','Cutterzy','Cutters'],['oline','O-line','O-line'],['dline','D-line','D-line'],['youth','U21','U21']].map(([id,pl,eng])=><option key={id} value={id}>{en?eng:pl}</option>)}</select>{plan?.reason&&<p className="mt-1 text-xs text-ufa-muted">{plan.reason==='preMatch'?(en?'Before match':'Przed meczem'):(en?'Recovery / reserves top-up':'Regeneracja / trening rezerwowych')}</p>}{s.overrides[`${date}|${slot}`]&&<button disabled={disabled} className="text-xs text-ufa-accent" onClick={()=>{delete s.overrides[`${date}|${slot}`];change()}}>{en?'Restore plan':'Przywróć plan'}</button>}</>}</td>
      })}</tr>)}</tbody></table></div>
    </>}
    <details open><summary className="font-semibold">{en?'Readiness and individual rules':'Gotowość i zasady indywidualne'}</summary><p className="my-2 text-xs text-ufa-muted">{en?`Estimate for ${next}, up to 28 days; assumes normal match participation, excludes future injuries. Risk is a workload indicator.`:`Prognoza na ${next}, maks. 28 dni; zakłada typowy udział w meczach, bez przyszłych urazów. Ryzyko jest wskaźnikiem obciążenia.`}</p>
      <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{(en?['Player','Freshness','Fatigue','Rhythm','7d load','Risk','Forecast','Group','Intensity','Today']:['Zawodnik','Świeżość','Zmęczenie','Rytm','Wysiłek 7d','Ryzyko','Prognoza','Grupa','Intensywność','Dzisiaj']).map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{(team.players??[]).map(p=>{
        const forecast=s.legacy?null:forecastTrainingPlayer(p,team,league,today,next),rule=trainingParticipation(p,today,s)
        const load=(p.workload?.history??[]).slice(-7).reduce((a,d)=>a+d.load,0)
        return <tr key={p.id} className="border-t border-ufa-border"><td className="p-2 whitespace-nowrap">{getPlayerFullName(p)}</td><td className="p-2">{Math.round(currentMatchStamina(p))}</td><td className="p-2">{Math.round(p.developmentFatigue??0)}</td><td className="p-2">{Math.round(p.matchSharpness??65)}</td><td className="p-2">{Math.round(load)}</td><td className="p-2">{riskLabels[workloadRisk(p)]}</td><td className="p-2">{forecast?.freshness??'—'}</td><td className="p-2"><select className={inputClass} disabled={disabled} value={p.trainingGroup??'auto'} onChange={e=>{p.trainingGroup=e.target.value==='auto'?undefined:e.target.value;change()}}>{['auto','handlers','cutters','oline','dline'].map(id=><option key={id} value={id}>{({auto:'Auto',handlers:'Handler',cutters:'Cutter',oline:'O-line',dline:'D-line'})[id]}</option>)}</select></td><td className="p-2"><select className={inputClass} disabled={disabled} value={p.trainingIntensity??'normal'} onChange={e=>{p.trainingIntensity=e.target.value;change()}}>{[['rest','Odpoczynek','Rest'],['light','Odciążenie','Light'],['normal','Normalna','Normal'],['extra','Zwiększona','Extra']].map(([id,pl,eng])=><option key={id} value={id}>{en?eng:pl}</option>)}</select></td><td className="p-2 text-xs">{reasons[rule.reason]?.[en?1:0]}</td></tr>
      })}</tbody></table></div></details>
    <details><summary className="font-semibold">{en?'Recent training results':'Ostatnie efekty treningów'}</summary>{(team.teamTraining.sessionLog??[]).slice(0,12).map((r,i)=><p className="border-t border-ufa-border py-2 text-sm" key={`${r.planId}-${i}`}>{r.date} · {SESSION_DEFS[r.sessionType]?.[en?'en':'pl']??r.focuses?.join(' / ')} · {en?'Quality':'Jakość'} {r.quality}% · {en?'Skill gains':'Przyrosty umiejętności'} {r.skillBumps} · {en?'Tactics':'Taktyka'} +{Number(r.tacticsDelta??0).toFixed(2)}</p>)}</details>
  </section>
}
